chat_example_client:
    path:     /client
    defaults: { _controller: ChatBundle:Default:exampleClient }

chat_example_client_get_messages:
    path:     /client/getMessages
    defaults: { _controller: ChatBundle:Default:getClientMessages }   
 
chat_example_admin:
    path:     /admin
    defaults: { _controller: ChatBundle:Default:exampleAdmin }
    
chat_admin:
    path:     /adminPanel
    defaults: { _controller: ChatBundle:Default:adminPanel }

chat_panel:
    path:     /clientPanel
    defaults: { _controller: ChatBundle:Default:clientPanel }

chat_start_gos_server:
    path:     /startGosServer
    defaults: { _controller: ChatBundle:Default:startGosServer }

chat_example_client_send_offline_message:
    path:     /client/sendOfflineMessage
    defaults: { _controller: ChatBundle:OfflineMessage:sendOfflineMessage }   
